{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ---------------------------------------------------------------------------
  # Initrd / hardware detection
  # ---------------------------------------------------------------------------

  boot.initrd.availableKernelModules = [
    # GENERATED BY nixos-generate-config
  ];

  boot.initrd.kernelModules = [ ];

  # ---------------------------------------------------------------------------
  # Runtime kernel modules
  # ---------------------------------------------------------------------------

  boot.kernelModules = [
    # GENERATED / required hardware modules only
  ];

  boot.extraModulePackages = [ ];

  # ---------------------------------------------------------------------------
  # Platform
  # ---------------------------------------------------------------------------

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # ---------------------------------------------------------------------------
  # CPU
  # ---------------------------------------------------------------------------

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
